Traceback (most recent call last):
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kamac\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from matplotlib.colors import LinearSegmentedColormap
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, roc_auc_score
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\__init__.py:26[0m
[0;32m     22[0m [38;5;28;01mdel[39;00m _hard_dependencies, _dependency, _missing_dependencies
[0;32m     24[0m [38;5;28;01mtry[39;00m:
[0;32m     25[0m     [38;5;66;03m# numpy compat[39;00m
[1;32m---> 26[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m [38;5;28;01mimport[39;00m (
[0;32m     27[0m         is_numpy_dev [38;5;28;01mas[39;00m _is_numpy_dev,  [38;5;66;03m# pyright: ignore[reportUnusedImport] # noqa: F401[39;00m
[0;32m     28[0m     )
[0;32m     29[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m _err:  [38;5;66;03m# pragma: no cover[39;00m
[0;32m     30[0m     _module [38;5;241m=[39m _err[38;5;241m.[39mname

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\compat\__init__.py:26[0m
[0;32m     17[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_constants[39;00m [38;5;28;01mimport[39;00m (
[0;32m     18[0m     IS64,
[0;32m     19[0m     ISMUSL,
[1;32m   (...)[0m
[0;32m     23[0m     PYPY,
[0;32m     24[0m )
[0;32m     25[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompressors[39;00m
[1;32m---> 26[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnumpy[39;00m [38;5;28;01mimport[39;00m is_numpy_dev
[0;32m     27[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyarrow[39;00m [38;5;28;01mimport[39;00m (
[0;32m     28[0m     pa_version_under10p1,
[0;32m     29[0m     pa_version_under11p0,
[1;32m   (...)[0m
[0;32m     33[0m     pa_version_under16p0,
[0;32m     34[0m )
[0;32m     36[0m [38;5;28;01mif[39;00m TYPE_CHECKING:

File [1;32m~\miniconda3\envs\ml_venv\lib\site-packages\pandas\compat\numpy\__init__.py:9[0m
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutil[39;00m[38;5;21;01m.[39;00m[38;5;21;01mversion[39;00m [38;5;28;01mimport[39;00m Version
[0;32m      8[0m [38;5;66;03m# numpy versioning[39;00m
[1;32m----> 9[0m _np_version [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43m__version__[49m
[0;32m     10[0m _nlv [38;5;241m=[39m Version(_np_version)
[0;32m     11[0m np_version_lt1p23 [38;5;241m=[39m _nlv [38;5;241m<[39m Version([38;5;124m"[39m[38;5;124m1.23[39m[38;5;124m"[39m)

[1;31mAttributeError[0m: module 'numpy' has no attribute '__version__'

